// ==========================================
// DBML: Sistema de Localização de Encomendas
// ==========================================

Table users {
  id int [pk, increment]
  name varchar
  email varchar [unique]
  role varchar [note: 'admin ou customer']
  created_at timestamp
}

Table packages {
  id int [pk, increment]
  tracking_number varchar [unique, note: 'Ex: PT123456789']
  user_id int [ref: > users.id, note: 'A quem pertence a encomenda']
  current_status varchar [note: 'Ex: pending, in_transit, delivered']
  destination_address varchar
  created_at timestamp
}

Table tracking_events {
  id int [pk, increment]
  package_id int [ref: > packages.id, note: 'A que encomenda pertence este evento']
  status varchar [note: 'Ex: Saiu do centro de distribuição']
  location varchar [note: 'Ex: Lisboa, PT (ou coordenadas GPS)']
  created_at timestamp
}