// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"basicAPI/ent/migrate"

	"basicAPI/ent/parcel"
	"basicAPI/ent/trackingevent"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Parcel is the client for interacting with the Parcel builders.
	Parcel *ParcelClient
	// TrackingEvent is the client for interacting with the TrackingEvent builders.
	TrackingEvent *TrackingEventClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Parcel = NewParcelClient(c.config)
	c.TrackingEvent = NewTrackingEventClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Parcel:        NewParcelClient(cfg),
		TrackingEvent: NewTrackingEventClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Parcel:        NewParcelClient(cfg),
		TrackingEvent: NewTrackingEventClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Parcel.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Parcel.Use(hooks...)
	c.TrackingEvent.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Parcel.Intercept(interceptors...)
	c.TrackingEvent.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ParcelMutation:
		return c.Parcel.mutate(ctx, m)
	case *TrackingEventMutation:
		return c.TrackingEvent.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ParcelClient is a client for the Parcel schema.
type ParcelClient struct {
	config
}

// NewParcelClient returns a client for the Parcel from the given config.
func NewParcelClient(c config) *ParcelClient {
	return &ParcelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `parcel.Hooks(f(g(h())))`.
func (c *ParcelClient) Use(hooks ...Hook) {
	c.hooks.Parcel = append(c.hooks.Parcel, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `parcel.Intercept(f(g(h())))`.
func (c *ParcelClient) Intercept(interceptors ...Interceptor) {
	c.inters.Parcel = append(c.inters.Parcel, interceptors...)
}

// Create returns a builder for creating a Parcel entity.
func (c *ParcelClient) Create() *ParcelCreate {
	mutation := newParcelMutation(c.config, OpCreate)
	return &ParcelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Parcel entities.
func (c *ParcelClient) CreateBulk(builders ...*ParcelCreate) *ParcelCreateBulk {
	return &ParcelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ParcelClient) MapCreateBulk(slice any, setFunc func(*ParcelCreate, int)) *ParcelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ParcelCreateBulk{err: fmt.Errorf("calling to ParcelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ParcelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ParcelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Parcel.
func (c *ParcelClient) Update() *ParcelUpdate {
	mutation := newParcelMutation(c.config, OpUpdate)
	return &ParcelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ParcelClient) UpdateOne(_m *Parcel) *ParcelUpdateOne {
	mutation := newParcelMutation(c.config, OpUpdateOne, withParcel(_m))
	return &ParcelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ParcelClient) UpdateOneID(id int) *ParcelUpdateOne {
	mutation := newParcelMutation(c.config, OpUpdateOne, withParcelID(id))
	return &ParcelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Parcel.
func (c *ParcelClient) Delete() *ParcelDelete {
	mutation := newParcelMutation(c.config, OpDelete)
	return &ParcelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ParcelClient) DeleteOne(_m *Parcel) *ParcelDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ParcelClient) DeleteOneID(id int) *ParcelDeleteOne {
	builder := c.Delete().Where(parcel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ParcelDeleteOne{builder}
}

// Query returns a query builder for Parcel.
func (c *ParcelClient) Query() *ParcelQuery {
	return &ParcelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeParcel},
		inters: c.Interceptors(),
	}
}

// Get returns a Parcel entity by its id.
func (c *ParcelClient) Get(ctx context.Context, id int) (*Parcel, error) {
	return c.Query().Where(parcel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ParcelClient) GetX(ctx context.Context, id int) *Parcel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEvents queries the events edge of a Parcel.
func (c *ParcelClient) QueryEvents(_m *Parcel) *TrackingEventQuery {
	query := (&TrackingEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(parcel.Table, parcel.FieldID, id),
			sqlgraph.To(trackingevent.Table, trackingevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, parcel.EventsTable, parcel.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ParcelClient) Hooks() []Hook {
	return c.hooks.Parcel
}

// Interceptors returns the client interceptors.
func (c *ParcelClient) Interceptors() []Interceptor {
	return c.inters.Parcel
}

func (c *ParcelClient) mutate(ctx context.Context, m *ParcelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ParcelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ParcelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ParcelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ParcelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Parcel mutation op: %q", m.Op())
	}
}

// TrackingEventClient is a client for the TrackingEvent schema.
type TrackingEventClient struct {
	config
}

// NewTrackingEventClient returns a client for the TrackingEvent from the given config.
func NewTrackingEventClient(c config) *TrackingEventClient {
	return &TrackingEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `trackingevent.Hooks(f(g(h())))`.
func (c *TrackingEventClient) Use(hooks ...Hook) {
	c.hooks.TrackingEvent = append(c.hooks.TrackingEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `trackingevent.Intercept(f(g(h())))`.
func (c *TrackingEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.TrackingEvent = append(c.inters.TrackingEvent, interceptors...)
}

// Create returns a builder for creating a TrackingEvent entity.
func (c *TrackingEventClient) Create() *TrackingEventCreate {
	mutation := newTrackingEventMutation(c.config, OpCreate)
	return &TrackingEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TrackingEvent entities.
func (c *TrackingEventClient) CreateBulk(builders ...*TrackingEventCreate) *TrackingEventCreateBulk {
	return &TrackingEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TrackingEventClient) MapCreateBulk(slice any, setFunc func(*TrackingEventCreate, int)) *TrackingEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TrackingEventCreateBulk{err: fmt.Errorf("calling to TrackingEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TrackingEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TrackingEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TrackingEvent.
func (c *TrackingEventClient) Update() *TrackingEventUpdate {
	mutation := newTrackingEventMutation(c.config, OpUpdate)
	return &TrackingEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TrackingEventClient) UpdateOne(_m *TrackingEvent) *TrackingEventUpdateOne {
	mutation := newTrackingEventMutation(c.config, OpUpdateOne, withTrackingEvent(_m))
	return &TrackingEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TrackingEventClient) UpdateOneID(id int) *TrackingEventUpdateOne {
	mutation := newTrackingEventMutation(c.config, OpUpdateOne, withTrackingEventID(id))
	return &TrackingEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TrackingEvent.
func (c *TrackingEventClient) Delete() *TrackingEventDelete {
	mutation := newTrackingEventMutation(c.config, OpDelete)
	return &TrackingEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TrackingEventClient) DeleteOne(_m *TrackingEvent) *TrackingEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TrackingEventClient) DeleteOneID(id int) *TrackingEventDeleteOne {
	builder := c.Delete().Where(trackingevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TrackingEventDeleteOne{builder}
}

// Query returns a query builder for TrackingEvent.
func (c *TrackingEventClient) Query() *TrackingEventQuery {
	return &TrackingEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTrackingEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a TrackingEvent entity by its id.
func (c *TrackingEventClient) Get(ctx context.Context, id int) (*TrackingEvent, error) {
	return c.Query().Where(trackingevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TrackingEventClient) GetX(ctx context.Context, id int) *TrackingEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPackage queries the package edge of a TrackingEvent.
func (c *TrackingEventClient) QueryPackage(_m *TrackingEvent) *ParcelQuery {
	query := (&ParcelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(trackingevent.Table, trackingevent.FieldID, id),
			sqlgraph.To(parcel.Table, parcel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, trackingevent.PackageTable, trackingevent.PackageColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TrackingEventClient) Hooks() []Hook {
	return c.hooks.TrackingEvent
}

// Interceptors returns the client interceptors.
func (c *TrackingEventClient) Interceptors() []Interceptor {
	return c.inters.TrackingEvent
}

func (c *TrackingEventClient) mutate(ctx context.Context, m *TrackingEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TrackingEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TrackingEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TrackingEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TrackingEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TrackingEvent mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Parcel, TrackingEvent []ent.Hook
	}
	inters struct {
		Parcel, TrackingEvent []ent.Interceptor
	}
)
