// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basicAPI/ent/parcel"
	"basicAPI/ent/predicate"
	"basicAPI/ent/trackingevent"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeParcel        = "Parcel"
	TypeTrackingEvent = "TrackingEvent"
)

// ParcelMutation represents an operation that mutates the Parcel nodes in the graph.
type ParcelMutation struct {
	config
	op              Op
	typ             string
	id              *int
	tracking_number *string
	status          *parcel.Status
	created_at      *time.Time
	updated_at      *time.Time
	clearedFields   map[string]struct{}
	events          map[int]struct{}
	removedevents   map[int]struct{}
	clearedevents   bool
	done            bool
	oldValue        func(context.Context) (*Parcel, error)
	predicates      []predicate.Parcel
}

var _ ent.Mutation = (*ParcelMutation)(nil)

// parcelOption allows management of the mutation configuration using functional options.
type parcelOption func(*ParcelMutation)

// newParcelMutation creates new mutation for the Parcel entity.
func newParcelMutation(c config, op Op, opts ...parcelOption) *ParcelMutation {
	m := &ParcelMutation{
		config:        c,
		op:            op,
		typ:           TypeParcel,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withParcelID sets the ID field of the mutation.
func withParcelID(id int) parcelOption {
	return func(m *ParcelMutation) {
		var (
			err   error
			once  sync.Once
			value *Parcel
		)
		m.oldValue = func(ctx context.Context) (*Parcel, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Parcel.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withParcel sets the old Parcel of the mutation.
func withParcel(node *Parcel) parcelOption {
	return func(m *ParcelMutation) {
		m.oldValue = func(context.Context) (*Parcel, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ParcelMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ParcelMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ParcelMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ParcelMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Parcel.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTrackingNumber sets the "tracking_number" field.
func (m *ParcelMutation) SetTrackingNumber(s string) {
	m.tracking_number = &s
}

// TrackingNumber returns the value of the "tracking_number" field in the mutation.
func (m *ParcelMutation) TrackingNumber() (r string, exists bool) {
	v := m.tracking_number
	if v == nil {
		return
	}
	return *v, true
}

// OldTrackingNumber returns the old "tracking_number" field's value of the Parcel entity.
// If the Parcel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ParcelMutation) OldTrackingNumber(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTrackingNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTrackingNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTrackingNumber: %w", err)
	}
	return oldValue.TrackingNumber, nil
}

// ResetTrackingNumber resets all changes to the "tracking_number" field.
func (m *ParcelMutation) ResetTrackingNumber() {
	m.tracking_number = nil
}

// SetStatus sets the "status" field.
func (m *ParcelMutation) SetStatus(pa parcel.Status) {
	m.status = &pa
}

// Status returns the value of the "status" field in the mutation.
func (m *ParcelMutation) Status() (r parcel.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Parcel entity.
// If the Parcel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ParcelMutation) OldStatus(ctx context.Context) (v parcel.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *ParcelMutation) ResetStatus() {
	m.status = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *ParcelMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ParcelMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Parcel entity.
// If the Parcel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ParcelMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ParcelMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *ParcelMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *ParcelMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Parcel entity.
// If the Parcel object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ParcelMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *ParcelMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddEventIDs adds the "events" edge to the TrackingEvent entity by ids.
func (m *ParcelMutation) AddEventIDs(ids ...int) {
	if m.events == nil {
		m.events = make(map[int]struct{})
	}
	for i := range ids {
		m.events[ids[i]] = struct{}{}
	}
}

// ClearEvents clears the "events" edge to the TrackingEvent entity.
func (m *ParcelMutation) ClearEvents() {
	m.clearedevents = true
}

// EventsCleared reports if the "events" edge to the TrackingEvent entity was cleared.
func (m *ParcelMutation) EventsCleared() bool {
	return m.clearedevents
}

// RemoveEventIDs removes the "events" edge to the TrackingEvent entity by IDs.
func (m *ParcelMutation) RemoveEventIDs(ids ...int) {
	if m.removedevents == nil {
		m.removedevents = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.events, ids[i])
		m.removedevents[ids[i]] = struct{}{}
	}
}

// RemovedEvents returns the removed IDs of the "events" edge to the TrackingEvent entity.
func (m *ParcelMutation) RemovedEventsIDs() (ids []int) {
	for id := range m.removedevents {
		ids = append(ids, id)
	}
	return
}

// EventsIDs returns the "events" edge IDs in the mutation.
func (m *ParcelMutation) EventsIDs() (ids []int) {
	for id := range m.events {
		ids = append(ids, id)
	}
	return
}

// ResetEvents resets all changes to the "events" edge.
func (m *ParcelMutation) ResetEvents() {
	m.events = nil
	m.clearedevents = false
	m.removedevents = nil
}

// Where appends a list predicates to the ParcelMutation builder.
func (m *ParcelMutation) Where(ps ...predicate.Parcel) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ParcelMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ParcelMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Parcel, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ParcelMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ParcelMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Parcel).
func (m *ParcelMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ParcelMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.tracking_number != nil {
		fields = append(fields, parcel.FieldTrackingNumber)
	}
	if m.status != nil {
		fields = append(fields, parcel.FieldStatus)
	}
	if m.created_at != nil {
		fields = append(fields, parcel.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, parcel.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ParcelMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case parcel.FieldTrackingNumber:
		return m.TrackingNumber()
	case parcel.FieldStatus:
		return m.Status()
	case parcel.FieldCreatedAt:
		return m.CreatedAt()
	case parcel.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ParcelMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case parcel.FieldTrackingNumber:
		return m.OldTrackingNumber(ctx)
	case parcel.FieldStatus:
		return m.OldStatus(ctx)
	case parcel.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case parcel.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Parcel field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ParcelMutation) SetField(name string, value ent.Value) error {
	switch name {
	case parcel.FieldTrackingNumber:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTrackingNumber(v)
		return nil
	case parcel.FieldStatus:
		v, ok := value.(parcel.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case parcel.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case parcel.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Parcel field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ParcelMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ParcelMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ParcelMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Parcel numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ParcelMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ParcelMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ParcelMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Parcel nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ParcelMutation) ResetField(name string) error {
	switch name {
	case parcel.FieldTrackingNumber:
		m.ResetTrackingNumber()
		return nil
	case parcel.FieldStatus:
		m.ResetStatus()
		return nil
	case parcel.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case parcel.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Parcel field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ParcelMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.events != nil {
		edges = append(edges, parcel.EdgeEvents)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ParcelMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case parcel.EdgeEvents:
		ids := make([]ent.Value, 0, len(m.events))
		for id := range m.events {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ParcelMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedevents != nil {
		edges = append(edges, parcel.EdgeEvents)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ParcelMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case parcel.EdgeEvents:
		ids := make([]ent.Value, 0, len(m.removedevents))
		for id := range m.removedevents {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ParcelMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedevents {
		edges = append(edges, parcel.EdgeEvents)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ParcelMutation) EdgeCleared(name string) bool {
	switch name {
	case parcel.EdgeEvents:
		return m.clearedevents
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ParcelMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Parcel unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ParcelMutation) ResetEdge(name string) error {
	switch name {
	case parcel.EdgeEvents:
		m.ResetEvents()
		return nil
	}
	return fmt.Errorf("unknown Parcel edge %s", name)
}

// TrackingEventMutation represents an operation that mutates the TrackingEvent nodes in the graph.
type TrackingEventMutation struct {
	config
	op              Op
	typ             string
	id              *int
	event_time      *time.Time
	location        *string
	status          *trackingevent.Status
	clearedFields   map[string]struct{}
	_package        *int
	cleared_package bool
	done            bool
	oldValue        func(context.Context) (*TrackingEvent, error)
	predicates      []predicate.TrackingEvent
}

var _ ent.Mutation = (*TrackingEventMutation)(nil)

// trackingeventOption allows management of the mutation configuration using functional options.
type trackingeventOption func(*TrackingEventMutation)

// newTrackingEventMutation creates new mutation for the TrackingEvent entity.
func newTrackingEventMutation(c config, op Op, opts ...trackingeventOption) *TrackingEventMutation {
	m := &TrackingEventMutation{
		config:        c,
		op:            op,
		typ:           TypeTrackingEvent,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTrackingEventID sets the ID field of the mutation.
func withTrackingEventID(id int) trackingeventOption {
	return func(m *TrackingEventMutation) {
		var (
			err   error
			once  sync.Once
			value *TrackingEvent
		)
		m.oldValue = func(ctx context.Context) (*TrackingEvent, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TrackingEvent.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTrackingEvent sets the old TrackingEvent of the mutation.
func withTrackingEvent(node *TrackingEvent) trackingeventOption {
	return func(m *TrackingEventMutation) {
		m.oldValue = func(context.Context) (*TrackingEvent, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TrackingEventMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TrackingEventMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TrackingEventMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TrackingEventMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TrackingEvent.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetEventTime sets the "event_time" field.
func (m *TrackingEventMutation) SetEventTime(t time.Time) {
	m.event_time = &t
}

// EventTime returns the value of the "event_time" field in the mutation.
func (m *TrackingEventMutation) EventTime() (r time.Time, exists bool) {
	v := m.event_time
	if v == nil {
		return
	}
	return *v, true
}

// OldEventTime returns the old "event_time" field's value of the TrackingEvent entity.
// If the TrackingEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TrackingEventMutation) OldEventTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEventTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEventTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEventTime: %w", err)
	}
	return oldValue.EventTime, nil
}

// ResetEventTime resets all changes to the "event_time" field.
func (m *TrackingEventMutation) ResetEventTime() {
	m.event_time = nil
}

// SetLocation sets the "location" field.
func (m *TrackingEventMutation) SetLocation(s string) {
	m.location = &s
}

// Location returns the value of the "location" field in the mutation.
func (m *TrackingEventMutation) Location() (r string, exists bool) {
	v := m.location
	if v == nil {
		return
	}
	return *v, true
}

// OldLocation returns the old "location" field's value of the TrackingEvent entity.
// If the TrackingEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TrackingEventMutation) OldLocation(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLocation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLocation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLocation: %w", err)
	}
	return oldValue.Location, nil
}

// ClearLocation clears the value of the "location" field.
func (m *TrackingEventMutation) ClearLocation() {
	m.location = nil
	m.clearedFields[trackingevent.FieldLocation] = struct{}{}
}

// LocationCleared returns if the "location" field was cleared in this mutation.
func (m *TrackingEventMutation) LocationCleared() bool {
	_, ok := m.clearedFields[trackingevent.FieldLocation]
	return ok
}

// ResetLocation resets all changes to the "location" field.
func (m *TrackingEventMutation) ResetLocation() {
	m.location = nil
	delete(m.clearedFields, trackingevent.FieldLocation)
}

// SetStatus sets the "status" field.
func (m *TrackingEventMutation) SetStatus(t trackingevent.Status) {
	m.status = &t
}

// Status returns the value of the "status" field in the mutation.
func (m *TrackingEventMutation) Status() (r trackingevent.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the TrackingEvent entity.
// If the TrackingEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TrackingEventMutation) OldStatus(ctx context.Context) (v trackingevent.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *TrackingEventMutation) ResetStatus() {
	m.status = nil
}

// SetPackageID sets the "package" edge to the Parcel entity by id.
func (m *TrackingEventMutation) SetPackageID(id int) {
	m._package = &id
}

// ClearPackage clears the "package" edge to the Parcel entity.
func (m *TrackingEventMutation) ClearPackage() {
	m.cleared_package = true
}

// PackageCleared reports if the "package" edge to the Parcel entity was cleared.
func (m *TrackingEventMutation) PackageCleared() bool {
	return m.cleared_package
}

// PackageID returns the "package" edge ID in the mutation.
func (m *TrackingEventMutation) PackageID() (id int, exists bool) {
	if m._package != nil {
		return *m._package, true
	}
	return
}

// PackageIDs returns the "package" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// PackageID instead. It exists only for internal usage by the builders.
func (m *TrackingEventMutation) PackageIDs() (ids []int) {
	if id := m._package; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetPackage resets all changes to the "package" edge.
func (m *TrackingEventMutation) ResetPackage() {
	m._package = nil
	m.cleared_package = false
}

// Where appends a list predicates to the TrackingEventMutation builder.
func (m *TrackingEventMutation) Where(ps ...predicate.TrackingEvent) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TrackingEventMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TrackingEventMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TrackingEvent, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TrackingEventMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TrackingEventMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TrackingEvent).
func (m *TrackingEventMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TrackingEventMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.event_time != nil {
		fields = append(fields, trackingevent.FieldEventTime)
	}
	if m.location != nil {
		fields = append(fields, trackingevent.FieldLocation)
	}
	if m.status != nil {
		fields = append(fields, trackingevent.FieldStatus)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TrackingEventMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case trackingevent.FieldEventTime:
		return m.EventTime()
	case trackingevent.FieldLocation:
		return m.Location()
	case trackingevent.FieldStatus:
		return m.Status()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TrackingEventMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case trackingevent.FieldEventTime:
		return m.OldEventTime(ctx)
	case trackingevent.FieldLocation:
		return m.OldLocation(ctx)
	case trackingevent.FieldStatus:
		return m.OldStatus(ctx)
	}
	return nil, fmt.Errorf("unknown TrackingEvent field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TrackingEventMutation) SetField(name string, value ent.Value) error {
	switch name {
	case trackingevent.FieldEventTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEventTime(v)
		return nil
	case trackingevent.FieldLocation:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLocation(v)
		return nil
	case trackingevent.FieldStatus:
		v, ok := value.(trackingevent.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	}
	return fmt.Errorf("unknown TrackingEvent field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TrackingEventMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TrackingEventMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TrackingEventMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TrackingEvent numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TrackingEventMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(trackingevent.FieldLocation) {
		fields = append(fields, trackingevent.FieldLocation)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TrackingEventMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TrackingEventMutation) ClearField(name string) error {
	switch name {
	case trackingevent.FieldLocation:
		m.ClearLocation()
		return nil
	}
	return fmt.Errorf("unknown TrackingEvent nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TrackingEventMutation) ResetField(name string) error {
	switch name {
	case trackingevent.FieldEventTime:
		m.ResetEventTime()
		return nil
	case trackingevent.FieldLocation:
		m.ResetLocation()
		return nil
	case trackingevent.FieldStatus:
		m.ResetStatus()
		return nil
	}
	return fmt.Errorf("unknown TrackingEvent field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TrackingEventMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m._package != nil {
		edges = append(edges, trackingevent.EdgePackage)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TrackingEventMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case trackingevent.EdgePackage:
		if id := m._package; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TrackingEventMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TrackingEventMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TrackingEventMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.cleared_package {
		edges = append(edges, trackingevent.EdgePackage)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TrackingEventMutation) EdgeCleared(name string) bool {
	switch name {
	case trackingevent.EdgePackage:
		return m.cleared_package
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TrackingEventMutation) ClearEdge(name string) error {
	switch name {
	case trackingevent.EdgePackage:
		m.ClearPackage()
		return nil
	}
	return fmt.Errorf("unknown TrackingEvent unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TrackingEventMutation) ResetEdge(name string) error {
	switch name {
	case trackingevent.EdgePackage:
		m.ResetPackage()
		return nil
	}
	return fmt.Errorf("unknown TrackingEvent edge %s", name)
}
