// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basicAPI/ent/parcel"
	"basicAPI/ent/predicate"
	"basicAPI/ent/trackingevent"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ParcelUpdate is the builder for updating Parcel entities.
type ParcelUpdate struct {
	config
	hooks    []Hook
	mutation *ParcelMutation
}

// Where appends a list predicates to the ParcelUpdate builder.
func (_u *ParcelUpdate) Where(ps ...predicate.Parcel) *ParcelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTrackingNumber sets the "tracking_number" field.
func (_u *ParcelUpdate) SetTrackingNumber(v string) *ParcelUpdate {
	_u.mutation.SetTrackingNumber(v)
	return _u
}

// SetNillableTrackingNumber sets the "tracking_number" field if the given value is not nil.
func (_u *ParcelUpdate) SetNillableTrackingNumber(v *string) *ParcelUpdate {
	if v != nil {
		_u.SetTrackingNumber(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ParcelUpdate) SetStatus(v parcel.Status) *ParcelUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ParcelUpdate) SetNillableStatus(v *parcel.Status) *ParcelUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ParcelUpdate) SetUpdatedAt(v time.Time) *ParcelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEventIDs adds the "events" edge to the TrackingEvent entity by IDs.
func (_u *ParcelUpdate) AddEventIDs(ids ...int) *ParcelUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the TrackingEvent entity.
func (_u *ParcelUpdate) AddEvents(v ...*TrackingEvent) *ParcelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the ParcelMutation object of the builder.
func (_u *ParcelUpdate) Mutation() *ParcelMutation {
	return _u.mutation
}

// ClearEvents clears all "events" edges to the TrackingEvent entity.
func (_u *ParcelUpdate) ClearEvents() *ParcelUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to TrackingEvent entities by IDs.
func (_u *ParcelUpdate) RemoveEventIDs(ids ...int) *ParcelUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to TrackingEvent entities.
func (_u *ParcelUpdate) RemoveEvents(v ...*TrackingEvent) *ParcelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ParcelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ParcelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ParcelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ParcelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ParcelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := parcel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ParcelUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := parcel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Parcel.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ParcelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(parcel.Table, parcel.Columns, sqlgraph.NewFieldSpec(parcel.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TrackingNumber(); ok {
		_spec.SetField(parcel.FieldTrackingNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(parcel.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(parcel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   parcel.EventsTable,
			Columns: []string{parcel.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   parcel.EventsTable,
			Columns: []string{parcel.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   parcel.EventsTable,
			Columns: []string{parcel.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{parcel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ParcelUpdateOne is the builder for updating a single Parcel entity.
type ParcelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ParcelMutation
}

// SetTrackingNumber sets the "tracking_number" field.
func (_u *ParcelUpdateOne) SetTrackingNumber(v string) *ParcelUpdateOne {
	_u.mutation.SetTrackingNumber(v)
	return _u
}

// SetNillableTrackingNumber sets the "tracking_number" field if the given value is not nil.
func (_u *ParcelUpdateOne) SetNillableTrackingNumber(v *string) *ParcelUpdateOne {
	if v != nil {
		_u.SetTrackingNumber(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ParcelUpdateOne) SetStatus(v parcel.Status) *ParcelUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ParcelUpdateOne) SetNillableStatus(v *parcel.Status) *ParcelUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ParcelUpdateOne) SetUpdatedAt(v time.Time) *ParcelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEventIDs adds the "events" edge to the TrackingEvent entity by IDs.
func (_u *ParcelUpdateOne) AddEventIDs(ids ...int) *ParcelUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the TrackingEvent entity.
func (_u *ParcelUpdateOne) AddEvents(v ...*TrackingEvent) *ParcelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the ParcelMutation object of the builder.
func (_u *ParcelUpdateOne) Mutation() *ParcelMutation {
	return _u.mutation
}

// ClearEvents clears all "events" edges to the TrackingEvent entity.
func (_u *ParcelUpdateOne) ClearEvents() *ParcelUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to TrackingEvent entities by IDs.
func (_u *ParcelUpdateOne) RemoveEventIDs(ids ...int) *ParcelUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to TrackingEvent entities.
func (_u *ParcelUpdateOne) RemoveEvents(v ...*TrackingEvent) *ParcelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the ParcelUpdate builder.
func (_u *ParcelUpdateOne) Where(ps ...predicate.Parcel) *ParcelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ParcelUpdateOne) Select(field string, fields ...string) *ParcelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Parcel entity.
func (_u *ParcelUpdateOne) Save(ctx context.Context) (*Parcel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ParcelUpdateOne) SaveX(ctx context.Context) *Parcel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ParcelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ParcelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ParcelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := parcel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ParcelUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := parcel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Parcel.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ParcelUpdateOne) sqlSave(ctx context.Context) (_node *Parcel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(parcel.Table, parcel.Columns, sqlgraph.NewFieldSpec(parcel.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Parcel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, parcel.FieldID)
		for _, f := range fields {
			if !parcel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != parcel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TrackingNumber(); ok {
		_spec.SetField(parcel.FieldTrackingNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(parcel.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(parcel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   parcel.EventsTable,
			Columns: []string{parcel.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   parcel.EventsTable,
			Columns: []string{parcel.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   parcel.EventsTable,
			Columns: []string{parcel.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Parcel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{parcel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
