// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basicAPI/ent/parcel"
	"basicAPI/ent/schema"
	"basicAPI/ent/trackingevent"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	parcelFields := schema.Parcel{}.Fields()
	_ = parcelFields
	// parcelDescCreatedAt is the schema descriptor for created_at field.
	parcelDescCreatedAt := parcelFields[2].Descriptor()
	// parcel.DefaultCreatedAt holds the default value on creation for the created_at field.
	parcel.DefaultCreatedAt = parcelDescCreatedAt.Default.(func() time.Time)
	// parcelDescUpdatedAt is the schema descriptor for updated_at field.
	parcelDescUpdatedAt := parcelFields[3].Descriptor()
	// parcel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	parcel.DefaultUpdatedAt = parcelDescUpdatedAt.Default.(func() time.Time)
	// parcel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	parcel.UpdateDefaultUpdatedAt = parcelDescUpdatedAt.UpdateDefault.(func() time.Time)
	trackingeventFields := schema.TrackingEvent{}.Fields()
	_ = trackingeventFields
	// trackingeventDescEventTime is the schema descriptor for event_time field.
	trackingeventDescEventTime := trackingeventFields[0].Descriptor()
	// trackingevent.DefaultEventTime holds the default value on creation for the event_time field.
	trackingevent.DefaultEventTime = trackingeventDescEventTime.Default.(func() time.Time)
}
