// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basicAPI/ent/parcel"
	"basicAPI/ent/predicate"
	"basicAPI/ent/trackingevent"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TrackingEventUpdate is the builder for updating TrackingEvent entities.
type TrackingEventUpdate struct {
	config
	hooks    []Hook
	mutation *TrackingEventMutation
}

// Where appends a list predicates to the TrackingEventUpdate builder.
func (_u *TrackingEventUpdate) Where(ps ...predicate.TrackingEvent) *TrackingEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLocation sets the "location" field.
func (_u *TrackingEventUpdate) SetLocation(v string) *TrackingEventUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *TrackingEventUpdate) SetNillableLocation(v *string) *TrackingEventUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *TrackingEventUpdate) ClearLocation() *TrackingEventUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TrackingEventUpdate) SetStatus(v trackingevent.Status) *TrackingEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TrackingEventUpdate) SetNillableStatus(v *trackingevent.Status) *TrackingEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPackageID sets the "package" edge to the Parcel entity by ID.
func (_u *TrackingEventUpdate) SetPackageID(id int) *TrackingEventUpdate {
	_u.mutation.SetPackageID(id)
	return _u
}

// SetPackage sets the "package" edge to the Parcel entity.
func (_u *TrackingEventUpdate) SetPackage(v *Parcel) *TrackingEventUpdate {
	return _u.SetPackageID(v.ID)
}

// Mutation returns the TrackingEventMutation object of the builder.
func (_u *TrackingEventUpdate) Mutation() *TrackingEventMutation {
	return _u.mutation
}

// ClearPackage clears the "package" edge to the Parcel entity.
func (_u *TrackingEventUpdate) ClearPackage() *TrackingEventUpdate {
	_u.mutation.ClearPackage()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TrackingEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrackingEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TrackingEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrackingEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrackingEventUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := trackingevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TrackingEvent.status": %w`, err)}
		}
	}
	if _u.mutation.PackageCleared() && len(_u.mutation.PackageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TrackingEvent.package"`)
	}
	return nil
}

func (_u *TrackingEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(trackingevent.Table, trackingevent.Columns, sqlgraph.NewFieldSpec(trackingevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(trackingevent.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(trackingevent.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(trackingevent.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.PackageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   trackingevent.PackageTable,
			Columns: []string{trackingevent.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(parcel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   trackingevent.PackageTable,
			Columns: []string{trackingevent.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(parcel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trackingevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TrackingEventUpdateOne is the builder for updating a single TrackingEvent entity.
type TrackingEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TrackingEventMutation
}

// SetLocation sets the "location" field.
func (_u *TrackingEventUpdateOne) SetLocation(v string) *TrackingEventUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *TrackingEventUpdateOne) SetNillableLocation(v *string) *TrackingEventUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *TrackingEventUpdateOne) ClearLocation() *TrackingEventUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TrackingEventUpdateOne) SetStatus(v trackingevent.Status) *TrackingEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TrackingEventUpdateOne) SetNillableStatus(v *trackingevent.Status) *TrackingEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPackageID sets the "package" edge to the Parcel entity by ID.
func (_u *TrackingEventUpdateOne) SetPackageID(id int) *TrackingEventUpdateOne {
	_u.mutation.SetPackageID(id)
	return _u
}

// SetPackage sets the "package" edge to the Parcel entity.
func (_u *TrackingEventUpdateOne) SetPackage(v *Parcel) *TrackingEventUpdateOne {
	return _u.SetPackageID(v.ID)
}

// Mutation returns the TrackingEventMutation object of the builder.
func (_u *TrackingEventUpdateOne) Mutation() *TrackingEventMutation {
	return _u.mutation
}

// ClearPackage clears the "package" edge to the Parcel entity.
func (_u *TrackingEventUpdateOne) ClearPackage() *TrackingEventUpdateOne {
	_u.mutation.ClearPackage()
	return _u
}

// Where appends a list predicates to the TrackingEventUpdate builder.
func (_u *TrackingEventUpdateOne) Where(ps ...predicate.TrackingEvent) *TrackingEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TrackingEventUpdateOne) Select(field string, fields ...string) *TrackingEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TrackingEvent entity.
func (_u *TrackingEventUpdateOne) Save(ctx context.Context) (*TrackingEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrackingEventUpdateOne) SaveX(ctx context.Context) *TrackingEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TrackingEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrackingEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrackingEventUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := trackingevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TrackingEvent.status": %w`, err)}
		}
	}
	if _u.mutation.PackageCleared() && len(_u.mutation.PackageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TrackingEvent.package"`)
	}
	return nil
}

func (_u *TrackingEventUpdateOne) sqlSave(ctx context.Context) (_node *TrackingEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(trackingevent.Table, trackingevent.Columns, sqlgraph.NewFieldSpec(trackingevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TrackingEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trackingevent.FieldID)
		for _, f := range fields {
			if !trackingevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != trackingevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(trackingevent.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(trackingevent.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(trackingevent.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.PackageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   trackingevent.PackageTable,
			Columns: []string{trackingevent.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(parcel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   trackingevent.PackageTable,
			Columns: []string{trackingevent.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(parcel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TrackingEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trackingevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
