// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basicAPI/ent/parcel"
	"basicAPI/ent/trackingevent"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TrackingEvent is the model entity for the TrackingEvent schema.
type TrackingEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EventTime holds the value of the "event_time" field.
	EventTime time.Time `json:"event_time,omitempty"`
	// Location holds the value of the "location" field.
	Location string `json:"location,omitempty"`
	// Status holds the value of the "status" field.
	Status trackingevent.Status `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TrackingEventQuery when eager-loading is set.
	Edges         TrackingEventEdges `json:"edges"`
	parcel_events *int
	selectValues  sql.SelectValues
}

// TrackingEventEdges holds the relations/edges for other nodes in the graph.
type TrackingEventEdges struct {
	// Package holds the value of the package edge.
	Package *Parcel `json:"package,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PackageOrErr returns the Package value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TrackingEventEdges) PackageOrErr() (*Parcel, error) {
	if e.Package != nil {
		return e.Package, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: parcel.Label}
	}
	return nil, &NotLoadedError{edge: "package"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TrackingEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case trackingevent.FieldID:
			values[i] = new(sql.NullInt64)
		case trackingevent.FieldLocation, trackingevent.FieldStatus:
			values[i] = new(sql.NullString)
		case trackingevent.FieldEventTime:
			values[i] = new(sql.NullTime)
		case trackingevent.ForeignKeys[0]: // parcel_events
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TrackingEvent fields.
func (_m *TrackingEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case trackingevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case trackingevent.FieldEventTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field event_time", values[i])
			} else if value.Valid {
				_m.EventTime = value.Time
			}
		case trackingevent.FieldLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value.Valid {
				_m.Location = value.String
			}
		case trackingevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = trackingevent.Status(value.String)
			}
		case trackingevent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field parcel_events", value)
			} else if value.Valid {
				_m.parcel_events = new(int)
				*_m.parcel_events = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TrackingEvent.
// This includes values selected through modifiers, order, etc.
func (_m *TrackingEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPackage queries the "package" edge of the TrackingEvent entity.
func (_m *TrackingEvent) QueryPackage() *ParcelQuery {
	return NewTrackingEventClient(_m.config).QueryPackage(_m)
}

// Update returns a builder for updating this TrackingEvent.
// Note that you need to call TrackingEvent.Unwrap() before calling this method if this TrackingEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TrackingEvent) Update() *TrackingEventUpdateOne {
	return NewTrackingEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TrackingEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TrackingEvent) Unwrap() *TrackingEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TrackingEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TrackingEvent) String() string {
	var builder strings.Builder
	builder.WriteString("TrackingEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_time=")
	builder.WriteString(_m.EventTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("location=")
	builder.WriteString(_m.Location)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// TrackingEvents is a parsable slice of TrackingEvent.
type TrackingEvents []*TrackingEvent
