// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basicAPI/ent/parcel"
	"basicAPI/ent/trackingevent"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TrackingEventCreate is the builder for creating a TrackingEvent entity.
type TrackingEventCreate struct {
	config
	mutation *TrackingEventMutation
	hooks    []Hook
}

// SetEventTime sets the "event_time" field.
func (_c *TrackingEventCreate) SetEventTime(v time.Time) *TrackingEventCreate {
	_c.mutation.SetEventTime(v)
	return _c
}

// SetNillableEventTime sets the "event_time" field if the given value is not nil.
func (_c *TrackingEventCreate) SetNillableEventTime(v *time.Time) *TrackingEventCreate {
	if v != nil {
		_c.SetEventTime(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *TrackingEventCreate) SetLocation(v string) *TrackingEventCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *TrackingEventCreate) SetNillableLocation(v *string) *TrackingEventCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TrackingEventCreate) SetStatus(v trackingevent.Status) *TrackingEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetPackageID sets the "package" edge to the Parcel entity by ID.
func (_c *TrackingEventCreate) SetPackageID(id int) *TrackingEventCreate {
	_c.mutation.SetPackageID(id)
	return _c
}

// SetPackage sets the "package" edge to the Parcel entity.
func (_c *TrackingEventCreate) SetPackage(v *Parcel) *TrackingEventCreate {
	return _c.SetPackageID(v.ID)
}

// Mutation returns the TrackingEventMutation object of the builder.
func (_c *TrackingEventCreate) Mutation() *TrackingEventMutation {
	return _c.mutation
}

// Save creates the TrackingEvent in the database.
func (_c *TrackingEventCreate) Save(ctx context.Context) (*TrackingEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TrackingEventCreate) SaveX(ctx context.Context) *TrackingEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TrackingEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TrackingEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TrackingEventCreate) defaults() {
	if _, ok := _c.mutation.EventTime(); !ok {
		v := trackingevent.DefaultEventTime()
		_c.mutation.SetEventTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TrackingEventCreate) check() error {
	if _, ok := _c.mutation.EventTime(); !ok {
		return &ValidationError{Name: "event_time", err: errors.New(`ent: missing required field "TrackingEvent.event_time"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TrackingEvent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := trackingevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TrackingEvent.status": %w`, err)}
		}
	}
	if len(_c.mutation.PackageIDs()) == 0 {
		return &ValidationError{Name: "package", err: errors.New(`ent: missing required edge "TrackingEvent.package"`)}
	}
	return nil
}

func (_c *TrackingEventCreate) sqlSave(ctx context.Context) (*TrackingEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TrackingEventCreate) createSpec() (*TrackingEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &TrackingEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(trackingevent.Table, sqlgraph.NewFieldSpec(trackingevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.EventTime(); ok {
		_spec.SetField(trackingevent.FieldEventTime, field.TypeTime, value)
		_node.EventTime = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(trackingevent.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(trackingevent.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.PackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   trackingevent.PackageTable,
			Columns: []string{trackingevent.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(parcel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.parcel_events = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TrackingEventCreateBulk is the builder for creating many TrackingEvent entities in bulk.
type TrackingEventCreateBulk struct {
	config
	err      error
	builders []*TrackingEventCreate
}

// Save creates the TrackingEvent entities in the database.
func (_c *TrackingEventCreateBulk) Save(ctx context.Context) ([]*TrackingEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TrackingEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TrackingEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TrackingEventCreateBulk) SaveX(ctx context.Context) []*TrackingEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TrackingEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TrackingEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
