// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basicAPI/ent/predicate"
	"basicAPI/ent/trackingevent"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TrackingEventDelete is the builder for deleting a TrackingEvent entity.
type TrackingEventDelete struct {
	config
	hooks    []Hook
	mutation *TrackingEventMutation
}

// Where appends a list predicates to the TrackingEventDelete builder.
func (_d *TrackingEventDelete) Where(ps ...predicate.TrackingEvent) *TrackingEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TrackingEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TrackingEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TrackingEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(trackingevent.Table, sqlgraph.NewFieldSpec(trackingevent.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TrackingEventDeleteOne is the builder for deleting a single TrackingEvent entity.
type TrackingEventDeleteOne struct {
	_d *TrackingEventDelete
}

// Where appends a list predicates to the TrackingEventDelete builder.
func (_d *TrackingEventDeleteOne) Where(ps ...predicate.TrackingEvent) *TrackingEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TrackingEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{trackingevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TrackingEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
