// Code generated by ent, DO NOT EDIT.

package trackingevent

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the trackingevent type in the database.
	Label = "tracking_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventTime holds the string denoting the event_time field in the database.
	FieldEventTime = "event_time"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgePackage holds the string denoting the package edge name in mutations.
	EdgePackage = "package"
	// Table holds the table name of the trackingevent in the database.
	Table = "tracking_events"
	// PackageTable is the table that holds the package relation/edge.
	PackageTable = "tracking_events"
	// PackageInverseTable is the table name for the Parcel entity.
	// It exists in this package in order to avoid circular dependency with the "parcel" package.
	PackageInverseTable = "parcels"
	// PackageColumn is the table column denoting the package relation/edge.
	PackageColumn = "parcel_events"
)

// Columns holds all SQL columns for trackingevent fields.
var Columns = []string{
	FieldID,
	FieldEventTime,
	FieldLocation,
	FieldStatus,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "tracking_events"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"parcel_events",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEventTime holds the default value on creation for the "event_time" field.
	DefaultEventTime func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusPENDING    Status = "PENDING"
	StatusIN_TRANSIT Status = "IN_TRANSIT"
	StatusDELIVERED  Status = "DELIVERED"
	StatusRETURNED   Status = "RETURNED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusIN_TRANSIT, StatusDELIVERED, StatusRETURNED:
		return nil
	default:
		return fmt.Errorf("trackingevent: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the TrackingEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventTime orders the results by the event_time field.
func ByEventTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventTime, opts...).ToFunc()
}

// ByLocation orders the results by the location field.
func ByLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocation, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPackageField orders the results by package field.
func ByPackageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPackageStep(), sql.OrderByField(field, opts...))
	}
}
func newPackageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PackageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PackageTable, PackageColumn),
	)
}
