// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Parcel is the predicate function for parcel builders.
type Parcel func(*sql.Selector)

// TrackingEvent is the predicate function for trackingevent builders.
type TrackingEvent func(*sql.Selector)
