package main

import (
	db "basicAPI/db/sqlc"
	"basicAPI/internal/data"
	"basicAPI/internal/handlers"
	"context"
	"flag"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"os"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

// TODO try to generate this later at compile time
const version = "1.0.0"

// Configuration Settings fot the application
type config struct {
	port int
	env  string
	db   struct {
		dsn          string
		maxOpenConns int
		maxIdleConns int
		maxIdleTime  string
	}
}

// This servers for the application to hold dependecies for the HTTP handlers, helpers and middleware
// This is a Singleton, so we only have one instance of it in the application.
type application struct {
	config   config
	logger   *log.Logger
	models   data.Models
	queries  *db.Queries         // O que o SQLC gera
	handlers *handlers.Container // Container de Handlers, que tem os handlers de cada recurso da API
}

func main() {
	// Instance of the config struct
	var cfg config

	// --- Configure Environment Variables ---
	// Read the value of the port and env command-line flags into the config struct.
	// 4000 is the default port for development environment if no corresponding flags are provided
	flag.IntVar(&cfg.port, "port", 4000, "API Server port")
	flag.StringVar(&cfg.env, "env", "development", "Environment (development|staging|production)")
	flag.StringVar(&cfg.db.dsn, "db-dsn", os.Getenv("POSTGRES_DB_DSN"), "PostgreSQL DSN")
	if cfg.db.dsn == "" {
		cfg.db.dsn = buildPostgresDSN()
	}
	flag.IntVar(&cfg.db.maxOpenConns, "db-max-open-conns", 25, "PostgreSQL max open connections")
	flag.IntVar(&cfg.db.maxIdleConns, "db-max-idle-conns", 25, "PostgreSQL max idle connections")
	flag.StringVar(&cfg.db.maxIdleTime, "db-max-idle-time", "15m", "PostgreSQL max idle time")

	flag.Parse()

	logger := log.New(os.Stdout, "", log.Ldate|log.Ltime)

	// Configure Database Connection Pool
	dbConn, err := openDB(cfg)
	if err != nil {
		logger.Fatal(err)
	}
	defer dbConn.Close()

	// Create a new instance of the Queries struct, which is generated by SQLC, and pass the database connection pool to it. This will allow us to execute our SQL queries using the methods defined in the Queries struct.
	queries := db.New(dbConn)

	// Create a new instance of the handlers.Container struct, which is a custom struct that we have defined to hold all of our HTTP handlers. We pass the Queries
	hContainer := handlers.NewContainer(queries, logger)

	// Create a new instance of the application struct, which is a custom struct that we have defined to hold all of our application dependencies. We pass the config, logger, database connection pool, and handlers container to it.
	app := &application{
		config:   cfg,
		logger:   logger,
		queries:  queries,
		handlers: hContainer,
	}

	// Execute HTTP Server
	err = app.serve()
	if err != nil {
		logger.Fatal(err)
	}
}

func (app *application) serve() error {
	srv := &http.Server{
		Addr:         fmt.Sprintf(":%d", app.config.port),
		Handler:      setupRouter(app.handlers),
		IdleTimeout:  time.Minute,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 30 * time.Second,
	}

	app.logger.Printf("starting %s server on %s", app.config.env, srv.Addr)
	return srv.ListenAndServe()
}

func openDB(cfg config) (*pgxpool.Pool, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	// O pgx usa uma config própria
	dbpool, err := pgxpool.New(ctx, cfg.db.dsn)
	if err != nil {
		return nil, err
	}

	if err := dbpool.Ping(ctx); err != nil {
		return nil, err
	}

	return dbpool, nil
}

func buildPostgresDSN() string {
	host := envOrDefault("DB_HOST", "localhost")
	port := envOrDefault("DB_PORT", "5435")
	user := envOrDefault("DB_USER", "myuser")
	password := envOrDefault("DB_PASSWORD", "secret")
	dbName := envOrDefault("DB_NAME", "greenlight")
	sslMode := envOrDefault("DB_SSLMODE", "disable")

	credentials := url.UserPassword(user, password)
	return fmt.Sprintf("postgres://%s@%s:%s/%s?sslmode=%s", credentials.String(), host, port, dbName, sslMode)
}

func envOrDefault(name, fallback string) string {
	value := os.Getenv(name)
	if value == "" {
		return fallback
	}
	return value
}
