// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ParcelsColumns holds the columns for the "parcels" table.
	ParcelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tracking_number", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "IN_TRANSIT", "DELIVERED", "RETURNED"}, Default: "PENDING"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ParcelsTable holds the schema information for the "parcels" table.
	ParcelsTable = &schema.Table{
		Name:       "parcels",
		Columns:    ParcelsColumns,
		PrimaryKey: []*schema.Column{ParcelsColumns[0]},
	}
	// TrackingEventsColumns holds the columns for the "tracking_events" table.
	TrackingEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "event_time", Type: field.TypeTime},
		{Name: "location", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "IN_TRANSIT", "DELIVERED", "RETURNED"}},
		{Name: "parcel_events", Type: field.TypeInt},
	}
	// TrackingEventsTable holds the schema information for the "tracking_events" table.
	TrackingEventsTable = &schema.Table{
		Name:       "tracking_events",
		Columns:    TrackingEventsColumns,
		PrimaryKey: []*schema.Column{TrackingEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tracking_events_parcels_events",
				Columns:    []*schema.Column{TrackingEventsColumns[4]},
				RefColumns: []*schema.Column{ParcelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ParcelsTable,
		TrackingEventsTable,
	}
)

func init() {
	TrackingEventsTable.ForeignKeys[0].RefTable = ParcelsTable
}
