// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Title     string             `json:"title"`
	Year      int32              `json:"year"`
	Runtime   int32              `json:"runtime"`
	Genres    []string           `json:"genres"`
	Version   int32              `json:"version"`
}

type User struct {
	ID           int64              `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash []byte             `json:"password_hash"`
	Activated    bool               `json:"activated"`
	Version      int32              `json:"version"`
}
