// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	ActivateUser(ctx context.Context, id int64) (User, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMovie(ctx context.Context, id int64) error
	GetMovie(ctx context.Context, id int64) (Movie, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListMovies(ctx context.Context, arg ListMoviesParams) ([]Movie, error)
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error)
}

var _ Querier = (*Queries)(nil)
